name: hsf-india-python
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - cxx-compiler
  - zstandard
  - zstd
  - clang-tools
  - fsspec
  - lz4
  - python-xxhash
  - pyarrow
  - cmake # needed to compile Geant examples
  - openssh # otherwise ssh is broken due to bug with openssl it seems
  - vim
  - awkward
  - h5py
  - hepunits
  - hist
  - numba
  - numexpr
  - numpy
  - pandas
  - particle
  - protobuf
  - pyarrow
  - pybind11
  - pyhf
  - matplotlib
  - uproot
  - vector
  - mplhep
  - requests
  - aiohttp
  - scikit-learn
  - tables
  - pip:
      - dm-haiku
      - ipympl
      - jax
      - jupyterlab-deck
      - jupyterlab-mathjax3
      - pyshp
      - servicex
      - bash_kernel
     
variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
